(function(g){var window=this;var jqa=function(a,b){return g.Ub(a,b)},$5=function(){},kqa=function(a){if(a.Bc&&"function"==typeof a.Bc)return a.Bc();
if(g.Da(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},lqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.Da(a))(0,g.y)(a,b,void 0);else{if(a.Pd&&"function"==typeof a.Pd)var c=a.Pd();else if(a.Bc&&"function"==typeof a.Bc)c=void 0;else if(g.La(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=kqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},a6=function(a){g.un(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},b6=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.zn(a.l,b,c)},c6=function(a){return(a=g.So(a))?new ActiveXObject(a):new XMLHttpRequest},d6=function(a,b){return b+" ["+a.Y+" "+a.D+" "+a.getStatus()+"]"},mqa=function(a){return"content-type"==a.toLowerCase()},e6=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.u.clearTimeout(a.F),a.F=null)},nqa=function(a){return g.Ld&&g.ld(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},f6=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},g6=function(a,b){if(a.g){e6(a);
var c=a.g,d=a.R[0]?g.Ha:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},h6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;f6(a);g6(a)},i6=function(a){return a.g?a.g.readyState:0},j6=function(a){if(a.i&&"undefined"!=typeof g.ZY)if(a.R[1]&&4==i6(a)&&2==a.getStatus())d6(a,"Local request error detected and ignored");
else if(a.B&&4==i6(a))g.Gg(a.Ew,0,a);else if(a.dispatchEvent("readystatechange"),4==i6(a)){d6(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!oqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<i6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";f6(a)}}finally{g6(a)}}},k6=function(a){g.Qf.call(this);
this.headers=new g.jn;this.M=a||null;this.i=!1;this.R=this.g=null;this.Y=this.D="";this.u=0;this.l="";this.o=this.aa=this.B=this.P=!1;this.A=0;this.F=null;this.X="";this.I=this.T=!1},l6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},pqa=function(a,b){var c=[];
g.Rk(b,function(d){try{var e=g.gp.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.fp(e)&&c.push(d):c.push(d)},a);
return c},qqa=function(a,b){var c=pqa(a,b);
(0,g.y)(c,function(d){g.gp.prototype.remove.call(this,d)},a)},m6=function(a){if(a.gd){if(a.gd.locationOverrideToken)return{locationOverrideToken:a.gd.locationOverrideToken};
if(null!=a.gd.latitudeE7&&null!=a.gd.longitudeE7)return{latitudeE7:a.gd.latitudeE7,longitudeE7:a.gd.longitudeE7}}return null},rqa=function(a,b){g.$a(a,b)||a.push(b)},n6=function(a){var b=0,c;
for(c in a)b++;return b},o6=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},sqa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},tqa=function(a,b,c,d){var e=new g.mn(null,void 0);
a&&g.nn(e,a);b&&g.on(e,b);c&&g.pn(e,c);d&&(e.i=d);return e},p6=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return sqa(a)},q6=function(){this.g=[];
this.i=[]},r6=function(a,b){g.lq[a]=!0;
var c=g.jq();c&&c.publish.apply(c,arguments);g.lq[a]=!1},s6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.jn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",uqa(this,a.capabilities||""),vqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},uqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(jqa,wqa)).forEach(function(c){a.capabilities.add(c)})},vqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},t6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},u6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},v6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},xqa=function(a){return new t6(a)},w6=function(a){return g.Ka(a)?(0,g.ge)(a,xqa):[]},x6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},y6=function(a){return g.Ka(a)?"["+(0,g.ge)(a,x6).join(",")+"]":"null"},z6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},yqa=function(a){return(0,g.ge)(a,function(b){return{key:b.id,
name:b.name}})},A6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},B6=function(a,b){return g.Xa(a,function(c){return u6(c,b)})},C6=function(a){try{var b=(0,g.It)(),c=(0,g.Ht)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},zqa=function(){var a=(0,g.Ht)();
a&&qqa(a,a.g.nf(!0))},D6=function(){var a=g.Kt("yt-remote-connected-devices")||[];
g.qb(a);return a},Aqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ge)(a,function(d,e){return 0==e?d:d.substring(c.length)})},E6=function(a){g.Jt("yt-remote-connected-devices",a,86400)},G6=function(){if(F6)return F6;
var a=g.Kt("yt-remote-device-id");a||(a=z6(),g.Jt("yt-remote-device-id",a,31536E3));for(var b=D6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return F6=d},H6=function(){var a=D6(),b=G6();
g.$a(a,b);g.Lt()&&g.sb(a,b);a=Aqa(a);if(0==a.length)try{g.Ms("remote_sid")}catch(c){}else try{g.Ls("remote_sid",a.join(","),-1)}catch(c){}},I6=function(){return g.Kt("yt-remote-session-browser-channel")},J6=function(){return g.Kt("yt-remote-local-screens")||[]},K6=function(){g.Jt("yt-remote-lounge-token-expiration",!0,86400)},Bqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ge)(J6(),function(d){return d.loungeToken}),c=(0,g.ge)(a,function(d){return d.loungeToken});
(0,g.mj)(c,function(d){return!g.$a(b,d)})&&K6();
g.Jt("yt-remote-local-screens",a,31536E3)},Cqa=function(a,b){g.Jt("yt-remote-session-browser-channel",a);
g.Jt("yt-remote-session-screen-id",b);var c=D6(),d=G6();g.$a(c,d)||c.push(d);E6(c);H6()},L6=function(a){a||(C6("yt-remote-session-screen-id"),C6("yt-remote-session-video-id"));
H6();a=D6();g.cb(a,G6());E6(a)},N6=function(){if(!M6){var a=g.qp();
a&&(M6=new g.ap(a))}return M6?!!M6.get("yt-remote-use-staging-server"):!1},O6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},P6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},R6=function(a){a.length?Q6(a.shift(),function(){R6(a)}):S6()},Dqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Q6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},S6=function(){var a=P6();
a&&a(!1,"No cast extension found")},T6=function(){if(Eqa){var a=2,b=P6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Q6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",S6,c)}},Fqa=function(){T6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);R6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},U6=function(a,b,c){g.A.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Yc=b;this.u=(0,g.x)(this.FD,this);this.g=!1;this.i=0;this.l=this.Aa=null;this.o=[]},V6=function(){},W6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ca=new g.An(this);this.i=new g.Fg;this.i.setInterval(250)},Y6=function(a,b,c){a.Zh=1;
a.ag=a6(b.clone());a.sh=c;a.u=!0;X6(a,null)},Z6=function(a,b,c,d,e){a.Zh=1;
a.ag=a6(b.clone());a.sh=null;a.u=c;e&&(a.xA=!1);X6(a,d)},X6=function(a,b){a.Ii=(0,g.D)();
$6(a);a.Eg=a.ag.clone();b6(a.Eg,"t",a.A);a.ol=0;a.wc=a.g.Tp(a.g.Wk()?b:null);0<a.Bq&&(a.bo=new g.Jl((0,g.x)(a.DB,a,a.wc),a.Bq));a.ca.da(a.wc,"readystatechange",a.yM);var c=a.Zg?g.bc(a.Zg):{};a.sh?(a.Ko="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.wc.send(a.Eg,a.Ko,a.sh,c)):(a.Ko="GET",a.xA&&!g.Nd&&(c.Connection="close"),a.wc.send(a.Eg,a.Ko,null,c));a.g.Be(1)},g7=function(a,b,c){for(var d=!0;!a.Og&&a.ol<c.length;){var e=Gqa(a,c);
if(e==a7){4==b&&(a.rg=4,b7(15),d=!1);break}else if(e==c7){a.rg=4;b7(16);d=!1;break}else d7(a,e)}4==b&&0==c.length&&(a.rg=1,b7(17),d=!1);a.Ee=a.Ee&&d;d||(e7(a),f7(a))},Gqa=function(a,b){var c=a.ol,d=b.indexOf("\n",c);
if(-1==d)return a7;c=Number(b.substring(c,d));if(isNaN(c))return c7;d+=1;if(d+c>b.length)return a7;var e=b.substr(d,c);a.ol=d+c;return e},j7=function(a,b){a.Ii=(0,g.D)();
$6(a);var c=b?window.location.hostname:"";a.Eg=a.ag.clone();g.un(a.Eg,"DOMAIN",c);g.un(a.Eg,"t",a.A);try{a.Ie=new ActiveXObject("htmlfile")}catch(n){e7(a);a.rg=7;b7(22);f7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in h7)k=h7[l];else if(l in i7)k=h7[l]=i7[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
h7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.Ie.open();a.Ie.write(g.Mc(c));a.Ie.close();a.Ie.parentWindow.m=(0,g.x)(a.NL,a);a.Ie.parentWindow.d=(0,g.x)(a.Ez,a,!0);a.Ie.parentWindow.rpcClose=(0,g.x)(a.Ez,a,!1);c=a.Ie.createElement("DIV");a.Ie.parentWindow.document.body.appendChild(c);d=g.Cc(a.Eg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.Be(1)},$6=function(a){a.Jt=(0,g.D)()+a.o;
k7(a,a.o)},k7=function(a,b){if(null!=a.Zi)throw Error("WatchDog timer not null");
a.Zi=l7((0,g.x)(a.XL,a),b)},m7=function(a){a.Zi&&(g.u.clearTimeout(a.Zi),a.Zi=null)},f7=function(a){a.g.Cw()||a.Og||a.g.On(a)},e7=function(a){m7(a);
g.qf(a.bo);a.bo=null;a.i.stop();g.Cn(a.ca);if(a.wc){var b=a.wc;a.wc=null;b.abort();b.dispose()}a.Ie&&(a.Ie=null)},d7=function(a,b){try{a.g.yz(a,b),a.g.Be(4)}catch(c){}},o7=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;n7(a,b,function(k){k?c(!0):g.u.setTimeout(function(){o7(a,b,c,d,f)},f)})}},n7=function(a,b,c){var d=new Image;
d.onload=function(){try{p7(d),c(!0)}catch(e){}};
d.onerror=function(){try{p7(d),c(!1)}catch(e){}};
d.onabort=function(){try{p7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{p7(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
o6(d,a)},p7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},q7=function(a){this.g=a;
this.i=new V6},s7=function(a){var b=r7(a.g,a.nj,"/mail/images/cleardot.gif");
a6(b);o7(b.toString(),5E3,(0,g.x)(a.MC,a),3,2E3);a.Be(1)},u7=function(a){var b=a.g.F;
if(null!=b)b7(5),b?(b7(11),t7(a.g,a,!1)):(b7(12),t7(a.g,a,!0));else if(a.Hd=new W6(a,void 0,void 0,void 0),a.Hd.Zg=a.zq,b=a.g,b=r7(b,b.Wk()?a.Uj:null,a.Aq),b7(5),!g.Ld||g.md(10))b6(b,"TYPE","xmlhttp"),Z6(a.Hd,b,!1,a.Uj,!1);else{b6(b,"TYPE","html");var c=a.Hd;a=!!a.Uj;c.Zh=3;c.ag=a6(b.clone());j7(c,a)}},v7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new V6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Hqa=function(a,b){this.g=a;
this.map=b;this.context=null},w7=function(a){g.sf.call(this,"statevent",a)},x7=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},Iqa=function(a){g.sf.call(this,"serverreachability",a)},Lqa=function(a){Jqa(a);
if(3==a.g){var b=a.Bk++,c=a.qm.clone();g.un(c,"SID",a.l);g.un(c,"RID",b);g.un(c,"TYPE","terminate");y7(a,c);b=new W6(a,a.l,b,void 0);b.Zh=2;b.ag=a6(c.clone());o6(new Image,b.ag.toString());b.Ii=(0,g.D)();$6(b)}Kqa(a)},Mqa=function(a){a.fD(1,0);
a.qm=r7(a,null,a.yq);z7(a)},Jqa=function(a){a.hg&&(a.hg.abort(),a.hg=null);
a.Tb&&(a.Tb.cancel(),a.Tb=null);a.qf&&(g.u.clearTimeout(a.qf),a.qf=null);A7(a);a.Ed&&(a.Ed.cancel(),a.Ed=null);a.og&&(g.u.clearTimeout(a.og),a.og=null)},Nqa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Hqa(a.bI++,b));2!=a.g&&3!=a.g||z7(a)},z7=function(a){a.Ed||a.og||(a.og=l7((0,g.x)(a.Dz,a),0),a.Sh=0)},Pqa=function(a,b){if(1==a.g){if(!b){a.Bk=Math.floor(1E5*Math.random());
var c=a.Bk++,d=new W6(a,"",c,void 0);d.Zg=null;var e=B7(a),f=a.qm.clone();g.un(f,"RID",c);g.un(f,"CVER","1");y7(a,f);Y6(d,f,e);a.Ed=d;a.g=2}}else 3==a.g&&(b?Oqa(a,b):0==a.i.length||a.Ed||Oqa(a))},Oqa=function(a,b){if(b)if(6<a.Pg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Bk-1;var d=B7(a)}else c=b.B,d=b.sh;else c=a.Bk++,d=B7(a);var e=a.qm.clone();g.un(e,"SID",a.l);g.un(e,"RID",c);g.un(e,"AID",a.li);y7(a,e);c=new W6(a,a.l,c,a.Sh+1);c.Zg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ed=c;Y6(c,e,d)},y7=function(a,b){if(a.Vc){var c=a.Vc.bw();
c&&g.Kb(c,function(d,e){g.un(b,e,d)})}},B7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Pg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Pg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},Qqa=function(a){a.Tb||a.qf||(a.B=1,a.qf=l7((0,g.x)(a.Cz,a),0),a.Lh=0)},C7=function(a){if(a.Tb||a.qf||3<=a.Lh)return!1;
a.B++;a.qf=l7((0,g.x)(a.Cz,a),Rqa(a,a.Lh));a.Lh++;return!0},t7=function(a,b,c){a.Io=c;
a.Ne=b.Bf;a.A||Mqa(a)},A7=function(a){null!=a.Tg&&(g.u.clearTimeout(a.Tg),a.Tg=null)},Rqa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},D7=function(a,b){if(2==b||9==b){var c=null;
a.Vc&&(c=null);var d=(0,g.x)(a.eN,a);c||(c=new g.mn("//www.google.com/images/cleardot.gif"),a6(c));n7(c.toString(),1E4,d)}else b7(2);Sqa(a,b)},Sqa=function(a,b){a.g=0;
a.Vc&&a.Vc.cv(b);Kqa(a);Jqa(a)},Kqa=function(a){a.g=0;
a.Ne=-1;if(a.Vc)if(0==a.o.length&&0==a.i.length)a.Vc.Hp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Vc.Hp(b)}},r7=function(a,b,c){var d=g.vn(c);
if(""!=d.g)b&&g.on(d,b+"."+d.g),g.pn(d,d.u);else{var e=window.location;d=tqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Cj&&g.Kb(a.Cj,function(f,k){g.un(d,k,f)});
g.un(d,"VER",a.Pg);y7(a,d);return d},l7=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},b7=function(a){E7.dispatchEvent(new w7(E7,a))},Tqa=function(){},Uqa=function(a,b){this.action=a;
this.params=b||{}},F7=function(a,b){g.A.call(this);
this.g=new g.J(this.FL,0,this);g.B(this,this.g);this.Yc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},G7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.$o;this.i=new F7(this.IM,this);this.g=null;this.jb=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},Vqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Io,sessionId:a.g.l,arrayId:a.g.li}},Wqa=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&Pqa(a.g),Lqa(a.g));a.D=0},H7=function(a){return!!a.g&&3==a.g.g},Xqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},I7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},J7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.bh(c+b,{})},K7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),oe:g.Qa(a.u,e)};c&&(a.wb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.dr(b,a)},ara=function(){var a=Yqa;
Zqa();L7.push(a);$qa(L7)},M7=function(a,b){Zqa();
var c=L7,d=bra(a,String(b));0==c.length?cra(d):($qa(c),(0,g.y)(c,function(e){e(d)}))},Zqa=function(){L7||(L7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",L7,void 0))},cra=function(a){var b=(N7+1)%50;
N7=b;O7[b]=a;P7||(P7=49==b)},$qa=function(a){var b=O7;
if(b[0]){var c=N7,d=P7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
O7=Array(50);N7=-1;P7=!1}},bra=function(a,b){var c=((0,g.D)()-dra)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},Q7=function(a){g.N.call(this);
this.B=a;this.g=[]},era=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},fra=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!A6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=era(a,b[d])||c;return c},gra=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},R7=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Aa=NaN},T7=function(a){Q7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;S7(this);this.info("Initializing with "+y6(this.g))},hra=function(a){if(a.g.length){var b=(0,g.ge)(a.g,function(d){return d.id}),c=J7(a.l,"/pairing/get_lounge_token_batch");
K7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.PD,a),(0,g.x)(a.OD,a))}},S7=function(a){var b=w6(J6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return fra(a,b)},U7=function(a,b){Bqa((0,g.ge)(a.g,v6));
b&&K6()},W7=function(a,b){g.N.call(this);
this.A=b;var c=g.Kt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;V7("Initialized with "+g.Kg(this.g))},ira=function(a,b,c){var d=J7(a.u,"/pairing/get_screen_availability");
K7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},X7=function(a,b){a:if(n6(b)!=n6(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(V7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.N("screenChange"));jra(a)},Y7=function(a){isNaN(a.l)||g.iq(a.l);
a.l=g.gq((0,g.x)(a.Ns,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},V7=function(a){M7("OnlineScreenService",a)},kra=function(a){var b={};
(0,g.y)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},jra=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Jt("yt-remote-online-screen-ids",a.join(","),60):C6("yt-remote-online-screen-ids")},Z7=function(a){Q7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};lra(this)},nra=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Rd();if(k=(c?B6(k,c):null)||B6(k,b)){k.uuid=b;var l=$7(a,k);ira(a.i,l,function(m){e(m?l:null)})}else c?mra(a,c,(0,g.x)(function(m){var n=$7(this,new t6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));ira(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},ora=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},mra=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={wb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.dr(J7(a.A,"/pairing/get_lounge_token_batch"),e)},pra=function(a){a.g=a.l.Rd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+y6(a.g))},lra=function(a){a8(a);
a.l=new T7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.XD,a));pra(a);a.o=w6(g.Kt("yt-remote-automatic-screen-cache")||[]);a8(a);a.info("Initializing automatic screens: "+y6(a.o));a.i=new W7(a.A,(0,g.x)(a.Rd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},$7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=B6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Jt("yt-remote-automatic-screen-cache",(0,g.ge)(a.o,v6)));a8(a);a.u[b.uuid]=b.id;g.Jt("yt-remote-device-id-map",a.u,31536E3);return b},a8=function(a){a.u=g.Kt("yt-remote-device-id-map")||{}},b8=function(a,b,c){g.N.call(this);
this.R=c;this.F=a;this.i=b;this.l=null},c8=function(a,b){M7(a.R,b)},d8=function(a,b){b8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.JN,this);this.u=(0,g.x)(this.iM,this);this.o=g.gq((0,g.x)(function(){qra(this,null)},this),12E4)},rra=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){c8(this,"Failed to send message: getMdxSessionStatus.")},a)):c8(a,"Sending yt message without session: "+g.Kg(b))},qra=function(a,b){g.iq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.Qn,a),d=(0,g.x)(a.Ud,a);a.tw(b,c,d,5)}}else a.Ud(Error("Waiting for session status timed out."))},e8=function(a,b,c){b8.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ha;this.A=NaN;this.I=(0,g.x)(this.MN,this);this.g=g.Ha},sra=function(a){a.g=a.F.IB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ha;
this.Qn(b)},a),(0,g.x)(function(b){this.g=g.Ha;
this.Ud(b)},a))},tra=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}N6()&&(b.env_useStageMdx=1);return g.$g(b)},f8=function(a,b){b8.call(this,a,b,"ManualSession");
this.g=g.gq((0,g.x)(this.ni,this,null),150)},g8=function(a,b,c,d){g.N.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.NK,this)},ura=function(a,b){return b?g.Xa(a.l,function(c){return u6(b,c.label)},a):null},h8=function(a){M7("Controller",a)},Yqa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},i8=function(a){return a.u||!!a.l.length||!!a.g},j8=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Bz,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ni(null)):a.N("yt-remote-cast2-session-change",null))},vra=function(a){var b=a.i.HB(),c=a.g&&a.g.i;
a=(0,g.ge)(b,function(d){c&&u6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=ura(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Bra=function(a,b,c,d,e,f,k){wra()?xra(b,e,f,k)&&(l8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?yra(a,c):(window.__onGCastApiAvailable=function(l,m){l?yra(a,c):(m8("Failed to load cast API: "+m),n8(!1),l8(!1),C6("yt-remote-cast-available"),C6("yt-remote-cast-receiver"),zra(),c(!1))},d?g.tq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Fqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?S6():(T6(),R6(Ara.map(Dqa))))):k8("Cannot initialize because not running Chrome")},zra=function(){k8("dispose");
var a=o8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);Cra(!1);g.oq(p8);p8.length=0},q8=function(){return!!g.Kt("yt-remote-cast-installed")},Dra=function(){var a=g.Kt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Era=function(){k8("clearCurrentReceiver");
C6("yt-remote-cast-receiver")},Fra=function(){return q8()?o8()?o8().getCastSession():(m8("getCastSelector: Cast is not initialized."),null):(m8("getCastSelector: Cast API is not installed!"),null)},s8=function(){q8()?o8()?r8()?(k8("Requesting cast selector."),o8().requestSession()):(k8("Wait for cast API to be ready to request the session."),p8.push(g.nq("yt-remote-cast2-api-ready",s8))):m8("requestCastSelector: Cast is not initialized."):m8("requestCastSelector: Cast API is not installed!")},t8=
function(a,b){r8()?o8().setConnectedScreenStatus(a,b):m8("setConnectedScreenStatus called before ready.")},wra=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.sx||a},Gra=function(a,b){o8().init(a,b)},xra=function(a,b,c,d){var e=!1;
o8()||(a=new g8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Jt("yt-remote-cast-available",f);r6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){k8("onReceiverSelected: "+f.friendlyName);
g.Jt("yt-remote-cast-receiver",f);r6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){k8("onReceiverResumed: "+f.friendlyName);
g.Jt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){k8("onSessionChange: "+x6(f));
f||C6("yt-remote-cast-receiver");r6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
k8("cloudview.createSingleton_: "+e);return e},o8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},yra=function(a,b){n8(!0);
l8(!1);Gra(a,function(c){c?(Cra(!0),g.qq("yt-remote-cast2-api-ready")):(m8("Failed to initialize cast API."),n8(!1),C6("yt-remote-cast-available"),C6("yt-remote-cast-receiver"),zra());b(c)})},k8=function(a){M7("cloudview",a)},m8=function(a){M7("cloudview",a)},n8=function(a){k8("setCastInstalled_ "+a);
g.Jt("yt-remote-cast-installed",a)},r8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Cra=function(a){k8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},l8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},u8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Oe=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},v8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Oe=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},w8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},x8=function(a,b){a.B=b;
a.A=(0,g.D)()},y8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},z8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&v8(a)},A8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Oe;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},C8=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new q6;this.l=this.i=null;this.F=(0,g.x)(this.KI,this);this.B=(0,g.x)(this.Ek,this);this.D=(0,g.x)(this.JI,this);this.H=(0,g.x)(this.YI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Mt,this),Hra(this))):c=3;0!=c&&(b?this.Mt(c):g.gq((0,g.x)(function(){this.Mt(c)},this),0));
var d=Fra();d&&B8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},D8=function(a){return new u8(a.o.getPlayerContextData())},Hra=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.KK,b),this))},a)},Ira=function(a){(0,g.y)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},E8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},G8=function(a,b,c){var d=D8(a);
x8(d,c);-1E3!=d.playerState&&(d.playerState=b);F8(a,d)},H8=function(a,b,c){a.o.sendMessage(b,c)},F8=function(a,b){Ira(a);
a.o.setPlayerContextData(A8(b));Hra(a)},B8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.Ek(null));
a.l=b;a.l&&(M7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.Ek(a.l.media[0]))},Jra=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=D8(a);b.contentId!=d.videoId&&M7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;x8(d,a.i.getEstimatedTime());F8(a,d)}else M7("CP","No cast media video. Ignoring state update.")},I8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),H8(this,b,c))},a)},J8=function(a,b,c){g.N.call(this);
this.u=NaN;this.I=!1;this.D=this.B=this.F=this.H=NaN;this.R=[];this.o=this.A=this.l=this.Pa=this.g=null;this.P=a;this.R.push(g.ms(window,"beforeunload",(0,g.x)(this.ID,this)));this.i=[];this.Pa=new u8;this.M=b.id;this.g=Kra(this,c);this.g.subscribe("handlerOpened",this.OI,this);this.g.subscribe("handlerClosed",this.LI,this);this.g.subscribe("handlerError",this.MI,this);this.g.subscribe("handlerMessage",this.NI,this);Xqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.Lt()&&g.Jt("yt-remote-session-video-id",d)},this)},K8=function(a){M7("conn",a)},Kra=function(a,b){return new G7(J7(a.P,"/bc"),b)},L8=function(a,b){a.N("proxyStateChange",b)},Lra=function(a){a.u=g.gq((0,g.x)(function(){K8("Connecting timeout");
this.Ph(1)},a),2E4)},M8=function(a){g.iq(a.u);
a.u=NaN},N8=function(a){g.iq(a.H);
a.H=NaN},Mra=function(a){O8(a);
a.F=g.gq((0,g.x)(function(){P8(this,"getNowPlaying")},a),2E4)},O8=function(a){g.iq(a.F);
a.F=NaN},Ora=function(a,b){b&&(M8(a),N8(a));
b==(H7(a.g)&&isNaN(a.u))?b&&(L8(a,1),P8(a,"getSubtitlesTrack")):b?(a.qw()&&a.Pa.reset(),L8(a,1),P8(a,"getNowPlaying"),Nra(a)):a.Ph(1)},Pra=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.Xb(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.N("remotePlayerChange"))},Qra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;z8(a.Pa,c,d);a.N("remoteQueueChange")},Sra=function(a,b){b.params=b.params||{};
Qra(a,b);Rra(a,b);a.N("autoplayDismissed")},Rra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
x8(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?Mra(a):O8(a);a.N("remotePlayerChange")},Tra=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);x8(a.Pa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Ura=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.N("remotePlayerChange")},Vra=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Wra=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Oe="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.N("previousNextChange")},Nra=function(a){g.iq(a.D);
a.D=g.gq((0,g.x)(a.Ph,a,1),864E5)},P8=function(a,b,c){c?K8("Sending: action="+b+", params="+g.Kg(c)):K8("Sending: action="+b);
a.g.sendMessage(b,c)},Q8=function(a){Q7.call(this,"ScreenServiceProxy");
this.Xc=a;this.i=[];this.i.push(this.Xc.$_s("screenChange",(0,g.x)(this.HN,this)));this.i.push(this.Xc.$_s("onlineScreenChange",(0,g.x)(this.pK,this)))},asa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Zp("MDX_CONFIG")||b;zqa();H6();R8||(R8=new I7(b?b.loungeApiHost:void 0),N6()&&(R8.g="/api/loungedev"));S8||(S8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",S8,void 0));Xra();var c=T8();if(!c){var d=new Z7(R8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=T8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Bra(a,d,function(m){m?U8()&&t8(U8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){r6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),V8("Initializing: "+g.Kg(b)),W8.push(g.nq("yt-remote-cast2-availability-change",function(){r6("yt-remote-receiver-availability-change")})),W8.push(g.nq("yt-remote-cast2-receiver-selected",function(){X8(null);
r6("yt-remote-auto-connect","cast-selector-receiver")})),W8.push(g.nq("yt-remote-cast2-receiver-resumed",function(){r6("yt-remote-receiver-resumed","cast-selector-receiver")})),W8.push(g.nq("yt-remote-cast2-session-change",Yra)),W8.push(g.nq("yt-remote-connection-change",function(m){m?t8(U8(),"YouTube TV"):Y8()||(t8(null,null),Era())})),a=Z8(),b.isAuto&&(a.id+="#dial"),g.Vq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),V8(" -- with channel params: "+
g.Kg(a)),Zra(a),c.start(),U8()||$ra())},csa=function(){var a=bsa();
q8()&&g.Kt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},bsa=function(){var a=T8().Xc.$_gos();
var b=$8();b&&a9()&&(A6(a,b)||a.push(b));return yqa(a)},b9=function(){var a=dsa();
!a&&q8()&&Dra()&&(a={key:"cast-selector-receiver",name:Dra()});return a},dsa=function(){var a=bsa(),b=$8();
b||(b=Y8());return g.Xa(a,function(c){return b&&u6(b,c.key)?!0:!1})},$8=function(){var a=U8();
if(!a)return null;var b=T8().Rd();return B6(b,a)},Yra=function(a){V8("remote.onCastSessionChange_: "+x6(a));
if(a){var b=$8();b&&b.id==a.id?t8(b.id,"YouTube TV"):(b&&c9(),d9(a,1))}else a9()&&c9()},c9=function(){r8()?o8().stopSession():m8("stopSession called before API ready.");
var a=a9();a&&(a.disconnect(1),e9(null))},f9=function(){var a=a9();
return!!a&&3!=a.getProxyState()},V8=function(a){M7("remote",a)},T8=function(){if(!g9){var a=g.w("yt.mdx.remote.screenService_");
g9=a?new Q8(a):null}return g9},U8=function(){return g.w("yt.mdx.remote.currentScreenId_")},esa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},fsa=function(){return g.w("yt.mdx.remote.connectData_")},X8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},a9=function(){return g.w("yt.mdx.remote.connection_")},e9=function(a){var b=a9();
X8(null);a||esa("");g.Ga("yt.mdx.remote.connection_",a,void 0);S8&&((0,g.y)(S8,function(c){c(a)}),S8.length=0);
b&&!a?r6("yt-remote-connection-change",!1):!b&&a&&r6("yt-remote-connection-change",!0)},Y8=function(){var a=g.Lt();
if(!a)return null;var b=T8().Rd();return B6(b,a)},d9=function(a,b){$8()&&$8();
if(h9)i9=a;else{esa(a.id);var c=new J8(R8,a,Z8());c.connect(b,fsa());c.subscribe("beforeDisconnect",function(d){r6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){a9()&&e9(null)});
e9(c)}},$ra=function(){var a=Y8();
a?(V8("Resume connection to: "+x6(a)),d9(a,0)):(L6(),Era(),V8("Skipping connecting because no session screen found."))},Xra=function(){var a=Z8();
if(g.Xb(a)){a=G6();var b=g.Kt("yt-remote-session-name")||"",c=g.Kt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},Z8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Zra=function(a){a?(g.Jt("yt-remote-session-app",a.app),g.Jt("yt-remote-session-name",a.name)):(C6("yt-remote-session-app"),C6("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},j9=function(a,b,c){g.A.call(this);
this.u=a;this.i=b;this.l=new g.Ws(this);g.B(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.KJ);this.l.K(b,"captionschanged",this.II);this.l.K(b,"captionssettingschanged",this.VA);this.l.K(b,"videoplayerreset",this.Rn);this.l.K(b,"mdxautoplaycancel",this.LC);this.P=this.l.K(b,"onVolumeChange",this.kz);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.xz,this);c.subscribe("remotePlayerChange",this.Gk,this);c.subscribe("remoteQueueChange",this.Rn,this);c.subscribe("autoplayUpNext",this.Yy,
this);c.subscribe("previousNextChange",this.uz,this);c.subscribe("nowAutoplaying",this.pz,this);c.subscribe("autoplayDismissed",this.Xy,this);this.suggestion=null;this.F=new g.RC(64);this.o=new g.J(this.TA,500,this);g.B(this,this.o);this.A=new g.J(this.UA,1E3,this);g.B(this,this.A);this.I=new U6(this.nN,0,this);g.B(this,this.I);this.B={};this.R=new g.J(this.vB,1E3,this);g.B(this,this.R);this.H=new g.Jl(this.fG,1E3,this);g.B(this,this.H);this.M=g.Ha;this.VA();this.Rn();this.Gk()},k9=function(a,b){a.u.Nc(b,
a.i.getVideoData().lengthSeconds)},gsa=function(a){k9(a,0);
a.o.stop();l9(a,new g.RC(64))},n9=function(a,b){if(m9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.KA(a.i.getVideoData(1).videoId,c);a.B=D8(a.g).g}},o9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Gf,m6(c));l9(a,new g.RC(1))},hsa=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{kR:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},m9=function(a){return D8(a.g).videoId==a.i.getVideoData(1).videoId},l9=function(a,b){a.A.stop();
var c=a.F;if(!g.XC(c,b)){var d=g.T(b,2);d!=g.T(a.F,2)&&g.OK(a.i,d);a.F=b;isa(a.u,c,b)}},p9=function(){g.V.call(this,{C:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{C:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{C:"div",G:"ytp-mdx-popup-title",V:"Du \u00e4r utloggad"},{C:"div",G:"ytp-mdx-popup-description",V:"Videor du tittar p\u00e5 kan l\u00e4ggas till i tv:ns visningshistorik och p\u00e5verka tv-rekommendationerna. Undvik detta genom att avbryta och logga in p\u00e5 YouTube p\u00e5 datorn."},{C:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Avbryt"},
{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],V:"Bekr\u00e4fta"}]}]}]});this.l=new g.IQ(this,250);g.B(this,this.l);this.B=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.B,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},q9=function(a){g.V.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.XP()]},{C:"div",G:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.IQ(this,250);g.B(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);jsa(this,g.KK(a))},jsa=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.WN("Fel p\u00e5 $RECEIVER_NAME",c):g.YC(b)||g.T(b,4)?g.WN("Spelas upp p\u00e5 $RECEIVER_NAME",c):g.WN("Ansluten till $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},r9=function(a,b){g.tU.call(this,"Spela upp p\u00e5",0,a,b);
this.l=a;this.B={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},s9=function(a){g.oL.call(this,a);
this.i={key:z6(),name:"Den h\u00e4r datorn"};this.u=null;this.o=[];this.F=this.g=null;this.B=[this.i];this.l=this.i;this.pk=new g.RC(64);this.I=0;this.Vm=-1;if(!g.xz(g.X(this.player))){a=this.player;var b=g.KD(a);b&&(b=b.An())&&(b=new r9(a,b),g.B(this,b));b=new q9(a);g.B(this,b);g.ZK(a,b.element,4);this.H=new p9;g.B(this,this.H);g.ZK(a,this.H.element,4);this.D=!!Y8()}this.A=null},t9=function(a){a.A&&(a.player.removeEventListener("presentingplayerstatechange",a.A),a.A=null)},isa=function(a,b,c){a.pk=
c;
a.player.N("presentingplayerstatechange",new g.aE(c,b))},u9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)c9();
else{var c;if(c=g.O(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))c=g.Zp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Zp("SESSION_INDEX")||g.Zp("LOGGED_IN"));c&&!a.D&&(g.YC(g.KK(a.player))||(a.A=(0,g.x)(a.pM,a),a.player.addEventListener("presentingplayerstatechange",a.A)),a.player.pauseVideo(),a.H.l.show(),a9()||(h9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<
f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Gf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=m6(c))&&(d.locationInfo=c);c=d}else c=null;V8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(X8(c||null),r8()?o8().setLaunchParams(c||null):m8("setLaunchParams called before ready.")):!c&&f9()&&U8()==b.key?r6("yt-remote-connection-change",!0):(c9(),
X8(c||null),c=T8().Rd(),(c=B6(c,b.key))&&d9(c,1))}},oqa=/^https?$/i,ksa=["POST",
"PUT"];g.Sa(k6,g.Qf);g.h=k6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.Y=b;this.P=!1;this.i=!0;this.g=this.M?c6(this.M):c6(g.vZ);this.R=this.M?this.M.getOptions():g.vZ.getOptions();this.g.onreadystatechange=(0,g.x)(this.Ew,this);try{$5(d6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){$5(d6(this,"Error opening Xhr: "+f.message));h6(this,f);return}a=
c||"";var e=this.headers.clone();d&&lqa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Pd(),mqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.$a(ksa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{e6(this),0<this.A&&(this.I=nqa(this.g),$5(d6(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.Fw,this)):this.F=g.Gg(this.Fw,this.A,this)),$5(d6(this,"Sending request")),this.B=!0,this.g.send(a),this.B=!1}catch(f){$5(d6(this,"Send error: "+f.message)),h6(this,f)}};
g.h.Fw=function(){"undefined"!=typeof g.ZY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,d6(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(d6(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),g6(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),g6(this,!0));k6.fb.U.call(this)};
g.h.Ew=function(){this.fa()||(this.aa||this.B||this.o?j6(this):this.MK())};
g.h.MK=function(){j6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<i6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.l)?this.l:String(this.l)};
var i7={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},h7={"'":"\\'"},lsa={};g.h=q6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Vma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.Bc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var wqa={gO:"atp",vQ:"ska",kQ:"que",LP:"mus",uQ:"sus",cP:"dsp",rQ:"seq"};s6.prototype.jg=function(){var a=new s6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var M6,F6="",Eqa=O6("loadCastFramework")||O6("loadCastApplicationFramework"),Ara=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(U6,g.A);g.h=U6.prototype;g.h.ED=function(a){this.o=arguments;this.g=!1;this.Aa?this.l=(0,g.D)()+this.Yc:this.Aa=g.Gg(this.u,this.Yc)};
g.h.stop=function(){this.Aa&&(g.u.clearTimeout(this.Aa),this.Aa=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();U6.fb.U.call(this)};
g.h.FD=function(){this.l?(this.Aa=g.Gg(this.u,this.l-(0,g.D)()),this.l=null):(this.Aa=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};V6.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
V6.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};g.h=W6.prototype;g.h.Zg=null;g.h.Ee=!1;g.h.Zi=null;g.h.Jt=null;g.h.Ii=null;g.h.Zh=null;g.h.ag=null;g.h.Eg=null;g.h.sh=null;g.h.wc=null;g.h.ol=0;g.h.Ie=null;g.h.Ko=null;g.h.rg=null;g.h.Vj=-1;g.h.xA=!0;g.h.Og=!1;g.h.Bq=0;g.h.bo=null;var c7={},a7={};g.h=W6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.yM=function(a){a=a.target;var b=this.bo;b&&3==i6(a)?b.Rj():this.DB(a)};
g.h.DB=function(a){try{if(a==this.wc)a:{var b=i6(this.wc),c=this.wc.u,d=this.wc.getStatus();if(g.Ld&&!g.md(10)||g.Nd&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!l6(this.wc))break a;this.Og||4!=b||7==c||(8==c||0>=d?this.g.Be(3):this.g.Be(2));m7(this);var e=this.wc.getStatus();this.Vj=e;var f=l6(this.wc);(this.Ee=200==e)?(4==b&&e7(this),this.u?(g7(this,b,f),g.Ch&&this.Ee&&3==b&&(this.ca.da(this.i,"tick",this.sM),this.i.start())):d7(this,f),this.Ee&&!this.Og&&(4==b?this.g.On(this):(this.Ee=
!1,$6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.rg=3,b7(13)):(this.rg=0,b7(14)),e7(this),f7(this))}}catch(k){this.wc&&l6(this.wc)}finally{}};
g.h.sM=function(){var a=i6(this.wc),b=l6(this.wc);this.ol<b.length&&(m7(this),g7(this,a,b),this.Ee&&4!=a&&$6(this))};
g.h.NL=function(a){l7((0,g.x)(this.ML,this,a),0)};
g.h.ML=function(a){this.Og||(m7(this),d7(this,a),$6(this))};
g.h.Ez=function(a){l7((0,g.x)(this.LL,this,a),0)};
g.h.LL=function(a){this.Og||(e7(this),this.Ee=a,this.g.On(this),this.g.Be(4))};
g.h.cancel=function(){this.Og=!0;e7(this)};
g.h.XL=function(){this.Zi=null;var a=(0,g.D)();0<=a-this.Jt?(2!=this.Zh&&this.g.Be(3),e7(this),this.rg=2,b7(18),f7(this)):k7(this,this.Jt-a)};
g.h.getLastError=function(){return this.rg};g.h=q7.prototype;g.h.zq=null;g.h.Hd=null;g.h.co=!1;g.h.Dw=null;g.h.om=null;g.h.kr=null;g.h.Aq=null;g.h.he=null;g.h.Bf=-1;g.h.Uj=null;g.h.nj=null;g.h.connect=function(a){this.Aq=a;a=r7(this.g,null,this.Aq);b7(3);this.Dw=(0,g.D)();var b=this.g.D;null!=b?(this.Uj=b[0],(this.nj=b[1])?(this.he=1,s7(this)):(this.he=2,u7(this))):(b6(a,"MODE","init"),this.Hd=new W6(this,void 0,void 0,void 0),this.Hd.Zg=this.zq,Z6(this.Hd,a,!1,null,!0),this.he=0)};
g.h.MC=function(a){if(a)this.he=2,u7(this);else{b7(4);var b=this.g;b.Ne=b.hg.Bf;D7(b,9)}a&&this.Be(2)};
g.h.Tp=function(a){return this.g.Tp(a)};
g.h.abort=function(){this.Hd&&(this.Hd.cancel(),this.Hd=null);this.Bf=-1};
g.h.Cw=function(){return!1};
g.h.yz=function(a,b){this.Bf=a.Vj;if(0==this.he)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ne=this.Bf;D7(c,2);return}this.Uj=c[0];this.nj=c[1]}else c=this.g,c.Ne=this.Bf,D7(c,2);else if(2==this.he)if(this.co)b7(7),this.kr=(0,g.D)();else if("11111"==b){if(b7(6),this.co=!0,this.om=(0,g.D)(),c=this.om-this.Dw,!g.Ld||g.md(10)||500>c)this.Bf=200,this.Hd.cancel(),b7(12),t7(this.g,this,!0)}else b7(8),this.om=this.kr=(0,g.D)(),this.co=!1};
g.h.On=function(){this.Bf=this.Hd.Vj;if(this.Hd.Ee)0==this.he?this.nj?(this.he=1,s7(this)):(this.he=2,u7(this)):2==this.he&&((!g.Ld||g.md(10)?!this.co:200>this.kr-this.om)?(b7(11),t7(this.g,this,!1)):(b7(12),t7(this.g,this,!0)));else{0==this.he?b7(9):2==this.he&&b7(10);var a=this.g;this.Hd.getLastError();a.Ne=this.Bf;D7(a,2)}};
g.h.Wk=function(){return this.g.Wk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Be=function(a){this.g.Be(a)};g.h=v7.prototype;g.h.Cj=null;g.h.Ed=null;g.h.Tb=null;g.h.yq=null;g.h.qm=null;g.h.Qu=null;g.h.Em=null;g.h.Bk=0;g.h.bI=0;g.h.Vc=null;g.h.og=null;g.h.qf=null;g.h.Tg=null;g.h.hg=null;g.h.Io=null;g.h.li=-1;g.h.nx=-1;g.h.Ne=-1;g.h.Sh=0;g.h.Lh=0;g.h.Pg=8;var E7=new g.Qf;g.Sa(w7,g.sf);g.Sa(x7,g.sf);g.Sa(Iqa,g.sf);g.h=v7.prototype;g.h.connect=function(a,b,c,d,e){b7(0);this.yq=b;this.Cj=c||{};d&&g.Ca(e)&&(this.Cj.OSID=d,this.Cj.OAID=e);this.A?(l7((0,g.x)(this.lv,this,a),100),Mqa(this)):this.lv(a)};
g.h.lv=function(a){this.hg=new q7(this);this.hg.zq=null;this.hg.i=this.u;this.hg.connect(a)};
g.h.Cw=function(){return 0==this.g};
g.h.Dz=function(a){this.og=null;Pqa(this,a)};
g.h.Cz=function(){this.qf=null;this.Tb=new W6(this,this.l,"rpc",this.B);this.Tb.Zg=null;this.Tb.Bq=0;var a=this.Qu.clone();g.un(a,"RID","rpc");g.un(a,"SID",this.l);g.un(a,"CI",this.Io?"0":"1");g.un(a,"AID",this.li);y7(this,a);if(!g.Ld||g.md(10))g.un(a,"TYPE","xmlhttp"),Z6(this.Tb,a,!0,this.Em,!1);else{g.un(a,"TYPE","html");var b=this.Tb,c=!!this.Em;b.Zh=3;b.ag=a6(a.clone());j7(b,c)}};
g.h.yz=function(a,b){if(0!=this.g&&(this.Tb==a||this.Ed==a))if(this.Ne=a.Vj,this.Ed==a&&3==this.g)if(7<this.Pg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Tb)if(this.Tb.Ii+3E3<this.Ed.Ii)A7(this),this.Tb.cancel(),this.Tb=null;else break a;C7(this);b7(19)}}else this.nx=c[1],0<this.nx-this.li&&37500>c[2]&&this.Io&&0==this.Lh&&!this.Tg&&(this.Tg=l7((0,g.x)(this.DI,this),6E3));else D7(this,11)}else b!=lsa.DO.g&&D7(this,11);else if(this.Tb==a&&
A7(this),!g.wb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.li=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Em=e[2],e=e[3],null!=e?this.Pg=e:this.Pg=6,this.g=3,this.Vc&&this.Vc.ev(),this.Qu=r7(this,this.Wk()?this.Em:null,this.yq),Qqa(this)):"stop"==e[0]&&D7(this,7):3==this.g&&("stop"==e[0]?D7(this,7):"noop"!=e[0]&&this.Vc&&this.Vc.dv(e),this.Lh=0)}}};
g.h.DI=function(){null!=this.Tg&&(this.Tg=null,this.Tb.cancel(),this.Tb=null,C7(this),b7(20))};
g.h.On=function(a){if(this.Tb==a){A7(this);this.Tb=null;var b=2}else if(this.Ed==a)this.Ed=null,b=1;else return;this.Ne=a.Vj;if(0!=this.g)if(a.Ee)1==b?(b=(0,g.D)()-a.Ii,E7.dispatchEvent(new x7(E7,a.sh?a.sh.length:0,b,this.Sh)),z7(this),this.o.length=0):Qqa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ne)){if(d=1==b)this.Ed||this.og||1==this.g||2<=this.Sh?d=!1:(this.og=l7((0,g.x)(this.Dz,this,a),Rqa(this,this.Sh)),this.Sh++,d=!0);d=!(d||2==b&&C7(this))}if(d)switch(c){case 1:D7(this,
5);break;case 4:D7(this,10);break;case 3:D7(this,6);break;case 7:D7(this,12);break;default:D7(this,2)}}};
g.h.fD=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.eN=function(a){a?b7(2):(b7(1),Sqa(this,8))};
g.h.Tp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new k6;a.T=!1;return a};
g.h.isActive=function(){return!!this.Vc&&this.Vc.isActive(this)};
g.h.Be=function(a){E7.dispatchEvent(new Iqa(E7,a))};
g.h.Wk=function(){return!(!g.Ld||g.md(10))};
g.h=Tqa.prototype;g.h.ev=function(){};
g.h.dv=function(){};
g.h.cv=function(){};
g.h.Hp=function(){};
g.h.bw=function(){return{}};
g.h.isActive=function(){return!0};g.Sa(F7,g.A);g.h=F7.prototype;g.h.FL=function(){this.Yc=Math.min(3E5,2*this.Yc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Yc+15E3*Math.random();g.Fo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Yc=5E3};g.Sa(G7,Tqa);g.h=G7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Mf=function(a){return this.l.ah(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.jb||(this.jb=!0,g.qf(this.l),Wqa(this),g.qf(this.i),this.i=null)};
g.h.fa=function(){return this.jb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new v7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Vc=null);d.Vc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.li):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):H7(this)&&Nqa(this.g,c)};
g.h.ev=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)Nqa(this.g,a[b])}this.N("handlerOpened")};
g.h.cv=function(a){var b=2==a&&401==this.g.Ne;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Hp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.bw=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.dv=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),Lqa(this.g)):this.N("handlerMessage",new Uqa(a[0],a[1]))};
g.h.IM=function(){this.i.isActive();var a=this.g,b=0;a.Tb&&b++;a.Ed&&b++;0==b&&this.connect(this.u,this.o)};I7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
I7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
I7.prototype.u=function(a){a(Error("request timed out"))};var dra=(0,g.D)(),L7=null,O7=Array(50),N7=-1,P7=!1;g.Sa(Q7,g.N);Q7.prototype.Rd=function(){return this.g};
Q7.prototype.contains=function(a){return!!A6(this.g,a)};
Q7.prototype.get=function(a){return a?B6(this.g,a):null};
Q7.prototype.info=function(a){M7(this.B,a)};g.t(R7,g.N);g.h=R7.prototype;g.h.start=function(){!this.g&&isNaN(this.Aa)&&this.GB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Aa)||(g.iq(this.Aa),this.Aa=NaN)};
g.h.U=function(){this.stop();g.N.prototype.U.call(this)};
g.h.GB=function(){this.Aa=NaN;this.g=g.dr(J7(this.A,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.FN,this),onError:(0,g.x)(this.EN,this),oe:(0,g.x)(this.GN,this)})};
g.h.FN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new t6(c))};
g.h.EN=function(a){this.g=null;a.status&&404==a.status?this.i>=msa.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=msa[this.i],this.Aa=g.gq((0,g.x)(this.GB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.GN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var msa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(T7,Q7);g.h=T7.prototype;g.h.start=function(){S7(this)&&this.N("screenChange");!g.Kt("yt-remote-lounge-token-expiration")&&hra(this);g.iq(this.i);this.i=g.gq((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){S7(this);era(this,a);U7(this,!1);this.N("screenChange");b(a);a.token||hra(this)};
g.h.remove=function(a,b){var c=S7(this);gra(this,a)&&(U7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Eo=function(a,b,c,d){var e=S7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,U7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.iq(this.i);T7.fb.U.call(this)};
g.h.PD=function(a){S7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}U7(this,!b);b&&M7(this.B,"Missed "+b+" lounge tokens.")};
g.h.OD=function(a){M7(this.B,"Requesting lounge tokens failed: "+a)};g.t(W7,g.N);g.h=W7.prototype;g.h.start=function(){var a=parseInt(g.Kt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?Y7(this):(this.o=(0,g.D)()+3E5,g.Jt("yt-remote-fast-check-period",this.o),this.Ns())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){V7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!B6(a,d)},this);
X7(this,b)};
g.h.U=function(){g.iq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.N.prototype.U.call(this)};
g.h.Ns=function(){g.iq(this.l);this.l=NaN;this.i&&this.i.abort();var a=kra(this);if(n6(a)){var b=J7(this.u,"/pairing/get_screen_availability");this.i=K7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.x)(this.iL,this,a),(0,g.x)(this.hL,this))}else X7(this,{}),Y7(this)};
g.h.iL=function(a,b){this.i=null;var c=g.Rb(kra(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;X7(this,d);Y7(this)}else this.Hb("Changing Screen set during request."),this.Ns()};
g.h.hL=function(a){this.Hb("Screen availability failed: "+a);this.i=null;Y7(this)};
g.h.Hb=function(a){M7("OnlineScreenService",a)};g.Sa(Z7,Q7);g.h=Z7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Eo=function(a,b,c,d){this.l.contains(a)?this.l.Eo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,M7(this.B,a),d(Error(a)))};
g.h.Rd=function(a){return a?this.g:g.fb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.HB=function(){return(0,g.Xd)(this.Rd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.IB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new R7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d($7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.IN=function(a,b,c,d){g.dr(J7(this.A,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new t6(f.screen||{});if(!k.name||ora(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);ora(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c($7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
oe:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.qf(this.l);g.qf(this.i);Z7.fb.U.call(this)};
g.h.XD=function(){pra(this);this.N("screenChange");this.i.update()};
Z7.prototype.dispose=Z7.prototype.dispose;g.Sa(b8,g.N);g.h=b8.prototype;g.h.Qn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Ud=function(a){this.fa()||(a&&c8(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){M7(this.R,a)};
g.h.KB=function(){return null};
g.h.Ws=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){c8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Ws("");b8.fb.U.call(this)};g.Sa(d8,b8);g.h=d8.prototype;g.h.Vs=function(a){if(this.g){if(this.g==a)return;c8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);rra(this)};
g.h.ni=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Ud()},this),(0,g.x)(function(){this.Ud(Error("Failed to stop receiver app."))},this)):this.Ud(Error("Stopping cast device witout session."))};
g.h.Ws=g.Ha;g.h.U=function(){this.info("disposeInternal");g.iq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;d8.fb.U.call(this)};
g.h.iM=function(a,b){if(!this.fa())if(b){var c=p6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":qra(this,c.screenId);break;default:c8(this,"Unknown youtube message: "+d)}}else c8(this,"Unable to parse message.")}else c8(this,"No data in message.")};
g.h.tw=function(a,b,c,d){nra(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(c8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.gq((0,g.x)(this.tw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.KB=function(){return this.g};
g.h.JN=function(a){this.fa()||a||(c8(this,"Cast session died."),this.Ud())};g.Sa(e8,b8);g.h=e8.prototype;g.h.Vs=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ni=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ha;g.iq(this.A);this.o?this.o.stop((0,g.x)(this.Ud,this,null),(0,g.x)(this.Ud,this,"Failed to stop DIAL device.")):this.Ud()};
g.h.U=function(){this.g();this.g=g.Ha;g.iq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;e8.fb.U.call(this)};
g.h.MN=function(a){this.fa()||a||(c8(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Ud())};
g.h.Nq=function(a){this.H=z6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,tra(this));a(b);sra(this)}else this.B=(0,g.x)(function(){g.iq(this.A);this.B=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,tra(this));a(c);sra(this)},this),this.A=g.gq((0,g.x)(function(){this.B()},this),100)};
g.h.sE=function(a,b,c){nra(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Qn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Nq(b,c)},this),(0,g.x)(function(d){c8(this,"Failed to get DIAL screen: "+d);
this.Nq(b,c)},this))};g.Sa(f8,b8);f8.prototype.stop=function(){this.Ud()};
f8.prototype.Vs=g.Ha;f8.prototype.ni=function(){g.iq(this.g);this.g=NaN;var a=B6(this.F.Rd(),this.i.label);a?this.Qn(a):this.Ud(Error("No such screen"))};
f8.prototype.U=function(){g.iq(this.g);this.g=NaN;f8.fb.U.call(this)};g.Sa(g8,g.N);g.h=g8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.RK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Az,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.fJ,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),ara(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.JB,this)),this.l=vra(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.N("yt-remote-cast2-availability-change",i8(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.SM=function(a,b){h8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)h8("Unsetting old screen status: "+this.g.i.friendlyName),j8(this,null)}if(a&&b){if(!this.g){c=B6(this.i.Rd(),a);if(!c){h8("setConnectedScreenStatus: Unknown screen.");return}var d=ura(this,c);d||(h8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
h8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);j8(this,new f8(this.i,d),!0)}this.g.Ws(b)}else h8("setConnectedScreenStatus: no screen.")};
g.h.TM=function(a){this.fa()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.ni(a):this.Hb("Setting connection data without a session")};
g.h.LN=function(){this.fa()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),j8(this,null)):h8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Az,this),(0,g.x)(this.oL,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.JB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.w("yt.mdx.remote.debug.handlers_")||[],Yqa);g.qf(this.g);g8.fb.U.call(this)};
g.h.Hb=function(a){M7("Controller",a)};
g.h.Bz=function(a,b){this.g==a&&(b||j8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.NK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),h8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)h8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{h8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:j8(this,
new f8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:j8(this,new e8(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:j8(this,new d8(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.fJ=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return h8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);j8(this,new e8(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.sE,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Nq,b))};
g.h.Az=function(a){if(!this.fa()){h8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)h8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),j8(this,new d8(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=B6(this.i.Rd(),c.label);d&&u6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(h8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new d8(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Bz,this,this.g)),this.g.ni(null));this.g.Vs(a)}}};
g.h.KN=function(){return this.g?this.g.KB():null};
g.h.oL=function(a){this.fa()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&j8(this,null))};
g.h.RK=function(a){h8("Receiver availability updated: "+a);if(!this.fa()){var b=i8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;i8(this)!=b&&this.N("yt-remote-cast2-availability-change",i8(this))}};
g.h.JB=function(){this.fa()||(this.l=vra(this),h8("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",i8(this)))};
g8.prototype.setLaunchParams=g8.prototype.TM;g8.prototype.setConnectedScreenStatus=g8.prototype.SM;g8.prototype.stopSession=g8.prototype.LN;g8.prototype.getCastSession=g8.prototype.KN;g8.prototype.requestSession=g8.prototype.requestSession;g8.prototype.init=g8.prototype.init;g8.prototype.dispose=g8.prototype.dispose;var p8=[];u8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";v8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Oe=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
u8.prototype.isAdPlaying=function(){return 1081==this.playerState};
u8.prototype.getDuration=function(){return this.u?this.D+w8(this):this.D};
u8.prototype.clone=function(){return new u8(A8(this))};g.t(C8,g.N);g.h=C8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,I8(this,"play")):H8(this,"play"),G8(this,1,y8(D8(this))),this.N("remotePlayerChange")):E8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,I8(this,"pause")):H8(this,"pause"),G8(this,2,y8(D8(this))),this.N("remotePlayerChange")):E8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=D8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,I8(this,"seekTo",{newTime:a}))}else H8(this,"seekTo",{newTime:a});G8(this,3,a);this.N("remotePlayerChange")}else E8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,I8(this,"stopVideo")):H8(this,"stopVideo");var a=D8(this);a.index=-1;a.videoId="";v8(a);F8(this,a);this.N("remotePlayerChange")}else E8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=D8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){M7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){M7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);H8(this,"setVolume",e)}c.muted=b;c.volume=a;F8(this,c)}else E8(this,g.Qa(this.setVolume,a,b))};
g.h.KA=function(a,b){if(1==this.g){var c=D8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.ec(d,c.g));H8(this,"setSubtitlesTrack",d);F8(this,c)}else E8(this,g.Qa(this.KA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();H8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=D8(this);d.audioTrackId=c;F8(this,d)}else E8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=D8(this);c=c||0;var m={videoId:a,currentIndex:c};z8(l,a,c);g.Ca(b)&&(x8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));H8(this,"setPlaylist",m);d||F8(this,l)};
g.h.Wn=function(a,b){if(1==this.g){if(a&&b){var c=D8(this);z8(c,a,b);F8(this,c)}H8(this,"previous")}else E8(this,g.Qa(this.Wn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=D8(this);z8(c,a,b);F8(this,c)}H8(this,"next")}else E8(this,g.Qa(this.nextVideo,a,b))};
g.h.Iv=function(){1==this.g?H8(this,"dismissAutoplay"):E8(this,this.Iv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.N.prototype.dispose.call(this)};
g.h.U=function(){Ira(this);this.o=null;this.u.clear();B8(this,null);g.N.prototype.U.call(this)};
g.h.Mt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.KK=function(a,b){this.N(a,b)};
g.h.KI=function(a){if(!a)this.Ek(null),B8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=D8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)M7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,F8(this,b)}};
g.h.Ek=function(a){M7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Jra(this),this.N("remotePlayerChange")};
g.h.JI=function(a){a?(Jra(this),this.N("remotePlayerChange")):this.Ek(null)};
g.h.wt=function(){H8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.YI=function(){var a=Fra();a&&B8(this,a)};
g.h.Hb=function(a){M7("CP",a)};g.t(J8,g.N);g.h=J8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;x8(this.Pa,m);this.o="UNSUPPORTED";K8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,I6())}else K8("Connecting without params"),this.g.connect({},a,I6());Lra(this)};
g.h.dispose=function(){this.fa()||(this.N("beforeDispose"),L8(this,3));g.N.prototype.dispose.call(this)};
g.h.U=function(){M8(this);O8(this);N8(this);g.iq(this.B);this.B=NaN;g.iq(this.D);this.D=NaN;this.l=null;g.ns(this.R);this.R.length=0;this.g.dispose();g.N.prototype.U.call(this);this.o=this.A=this.i=this.Pa=this.g=null};
g.h.ID=function(){this.Ph(2)};
g.h.OI=function(){K8("Channel opened");this.I&&(this.I=!1,N8(this),this.H=g.gq((0,g.x)(function(){K8("Timing out waiting for a screen.");this.Ph(1)},this),15E3));
Cqa(Vqa(this.g),this.M)};
g.h.LI=function(){K8("Channel closed");isNaN(this.u)?L6(!0):L6();this.dispose()};
g.h.MI=function(a){L6();isNaN(this.Kj())?(K8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,K8("Channel error: "+a+" with reconnection in "+this.Kj()+" ms"),L8(this,2))};
g.h.NI=function(a){a.params?K8("Received: action="+a.action+", params="+g.Kg(a.params)):K8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=p6(a.params.devices);this.i=(0,g.ge)(a,function(c){return new s6(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Ora(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Ora(this,!1);break;case "remoteConnected":var b=new s6(p6(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||rqa(this.i,b);
break;case "remoteDisconnected":b=new s6(p6(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Qra(this,a);break;case "nowPlaying":Sra(this,a);break;case "onStateChange":Rra(this,a);break;case "onAdStateChange":Tra(this,a);break;case "onVolumeChanged":Ura(this,a);break;case "onSubtitlesTrackChanged":Pra(this,a);break;case "nowAutoplaying":Vra(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Wra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:K8("Unrecognized action: "+a.action)}};
g.h.FM=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&P8(this,"getNowPlaying")}};
g.h.yD=function(){var a=3;this.fa()||(a=0,isNaN(this.Kj())?H7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Ph=function(a){K8("Disconnecting with "+a);M8(this);this.N("beforeDisconnect",a);1==a&&L6();Wqa(this.g,a);this.dispose()};
g.h.xD=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),z8(a,this.l,a.index));return A8(a)};
g.h.UM=function(a){var b=new u8(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.iq(this.B),this.B=g.gq((0,g.x)(this.FM,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&y8(this.Pa)==y8(b)&&g.Kg(this.Pa.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.y)(c,function(d){this.N(d)},this)};
g.h.qw=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Kj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.qD=function(){return this.o||"UNSUPPORTED"};
g.h.rD=function(){return this.A||""};
g.h.DN=function(){if(!isNaN(this.Kj())){var a=this.g.i;g.Go(a.g);a.start()}};
g.h.MM=function(a,b){P8(this,a,b);Nra(this)};
J8.prototype.subscribe=J8.prototype.subscribe;J8.prototype.unsubscribeByKey=J8.prototype.Mf;J8.prototype.getProxyState=J8.prototype.yD;J8.prototype.disconnect=J8.prototype.Ph;J8.prototype.getPlayerContextData=J8.prototype.xD;J8.prototype.setPlayerContextData=J8.prototype.UM;J8.prototype.getOtherConnectedRemoteId=J8.prototype.qw;J8.prototype.getReconnectTimeout=J8.prototype.Kj;J8.prototype.getAutoplayMode=J8.prototype.qD;J8.prototype.getAutoplayVideoId=J8.prototype.rD;J8.prototype.reconnect=J8.prototype.DN;
J8.prototype.sendMessage=J8.prototype.MM;g.t(Q8,Q7);g.h=Q8.prototype;g.h.Rd=function(a){return this.Xc.$_gs(a)};
g.h.contains=function(a){return!!this.Xc.$_c(a)};
g.h.get=function(a){return this.Xc.$_g(a)};
g.h.start=function(){this.Xc.$_st()};
g.h.add=function(a,b,c){this.Xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Xc.$_r(a,b,c)};
g.h.Eo=function(a,b,c,d){this.Xc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Xc.$_ubk(this.i[a]);this.i.length=0;this.Xc=null;Q7.prototype.U.call(this)};
g.h.HN=function(){this.N("screenChange")};
g.h.pK=function(){this.N("onlineScreenChange")};
Z7.prototype.$_st=Z7.prototype.start;Z7.prototype.$_gspc=Z7.prototype.IN;Z7.prototype.$_gsppc=Z7.prototype.IB;Z7.prototype.$_c=Z7.prototype.contains;Z7.prototype.$_g=Z7.prototype.get;Z7.prototype.$_a=Z7.prototype.add;Z7.prototype.$_un=Z7.prototype.Eo;Z7.prototype.$_r=Z7.prototype.remove;Z7.prototype.$_gs=Z7.prototype.Rd;Z7.prototype.$_gos=Z7.prototype.HB;Z7.prototype.$_s=Z7.prototype.subscribe;Z7.prototype.$_ubk=Z7.prototype.Mf;var i9=null,h9=!1,R8=null,S8=null,g9=null,W8=[];g.t(j9,g.A);g.h=j9.prototype;
g.h.U=function(){g.A.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.xz,this);this.g.unsubscribe("remotePlayerChange",this.Gk,this);this.g.unsubscribe("remoteQueueChange",this.Rn,this);this.g.unsubscribe("autoplayUpNext",this.Yy,this);this.g.unsubscribe("previousNextChange",this.uz,this);this.g.unsubscribe("nowAutoplaying",this.pz,this);this.g.unsubscribe("autoplayDismissed",this.Xy,this);this.g=this.u=null};
g.h.Tx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(m9(this)){if(!D8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==D8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Rj(c[0],c[1]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":c=c[0],m9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();o9(this,0==c?void 0:c);break;case "control_seek":o9(this,c[0]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":c=c[0],m9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.II=function(a){this.I.ED(a)};
g.h.nN=function(a){this.Tx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.VA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||n9(this,a)};
g.h.kz=function(a){if(m9(this)){this.g.unsubscribe("remotePlayerChange",this.Gk,this);var b=Math.round(a.volume);a=!!a.muted;var c=D8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.R.start();this.g.subscribe("remotePlayerChange",this.Gk,this)}};
g.h.KJ=function(){g.Xb(this.B)||hsa(this,this.B);this.D=!1};
g.h.xz=function(a,b){this.A.stop();2==b&&this.UA()};
g.h.Gk=function(){if(m9(this)){this.o.stop();var a=D8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Vm=1;break;case 1082:case 1083:this.u.Vm=0;break;default:this.u.Vm=-1}switch(a.playerState){case 1081:case 1:l9(this,new g.RC(8));this.TA();break;case 1085:case 3:l9(this,new g.RC(9));break;case 1083:case 0:l9(this,new g.RC(2));this.H.stop();k9(this,this.i.getVideoData().lengthSeconds);break;case 1084:l9(this,new g.RC(4));break;case 2:l9(this,new g.RC(4));k9(this,y8(a));
break;case -1:l9(this,new g.RC(64));break;case -1E3:l9(this,new g.RC(128,{errorCode:"mdx.remoteerror",errorMessage:"Det h\u00e4r videoklippet \u00e4r inte tillg\u00e4ngligt f\u00f6r fj\u00e4rruppspelning."}))}a=D8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,hsa(this,a));a=D8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.R.isActive()||this.vB()}else gsa(this)};
g.h.uz=function(){this.i.N("mdxpreviousnextchange")};
g.h.Rn=function(){m9(this)||gsa(this)};
g.h.LC=function(){this.g.Iv()};
g.h.Yy=function(a){a&&(a=g.dr("/watch_queue_ajax",{method:"GET",td:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.QL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.QL=function(a,b){var c=new g.BB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.pz=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Xy=function(){this.i.N("mdxautoplaycanceled")};
g.h.fG=function(a,b){-1==D8(this.g).playerState?o9(this,a):b&&this.g.seekTo(a)};
g.h.vB=function(){if(m9(this)){var a=D8(this.g);this.l.Na(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.K(this.i,"onVolumeChange",this.kz)}};
g.h.TA=function(){this.o.stop();if(!this.g.fa()){var a=D8(this.g);1==a.playerState&&l9(this,new g.RC(8));k9(this,y8(a));this.o.start()}};
g.h.UA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(p9,g.V);p9.prototype.o=function(){r6("mdx-privacy-popup-cancel");this.l.hide()};
p9.prototype.A=function(){r6("mdx-privacy-popup-confirm");this.l.hide()};g.t(q9,g.V);q9.prototype.u=function(a){jsa(this,a.state)};g.t(r9,g.tU);r9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.B=g.tb(a,this.A,this),g.vU(this,(0,g.ge)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.me(this.A(a)),this.enable(!0)):this.enable(!1)};
r9.prototype.A=function(a){return a.key};
r9.prototype.Ae=function(a){return"cast-selector-receiver"==a?"Casta \u2026":this.B[a].name};
r9.prototype.Lc=function(a){g.tU.prototype.Lc.call(this,a);this.l.setOption("remote","currentReceiver",this.B[a]);this.o.ob()};g.t(s9,g.oL);g.h=s9.prototype;
g.h.create=function(){asa(g.hz(g.X(this.player)));this.o.push(g.nq("yt-remote-before-disconnect",this.FI,this));this.o.push(g.nq("yt-remote-connection-change",this.SK,this));this.o.push(g.nq("yt-remote-receiver-availability-change",this.vz,this));this.o.push(g.nq("yt-remote-auto-connect",this.QK,this));this.o.push(g.nq("yt-remote-receiver-resumed",this.PK,this));this.o.push(g.nq("mdx-privacy-popup-confirm",this.vM,this));this.o.push(g.nq("mdx-privacy-popup-cancel",this.uM,this));this.vz()};
g.h.load=function(){this.player.cancelPlayback();g.oL.prototype.load.call(this);this.u=new j9(this,this.player,this.g);var a=(a=fsa())?a.currentTime:0;var b=f9()?new C8(a9(),void 0):null;0==a&&b&&(a=y8(D8(b)));0!=a&&this.Nc(a);isa(this,this.pk,this.pk);g.vY(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.oL.prototype.unload.call(this);g.vY(this.player.app,5);t9(this)};
g.h.U=function(){g.oq(this.o);g.oL.prototype.U.call(this)};
g.h.bf=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Tx.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Vm};
g.h.AD=function(){return this.loaded?this.u.suggestion:null};
g.h.Oe=function(){return this.g?D8(this.g).Oe:!1};
g.h.hasNext=function(){return this.g?D8(this.g).hasNext:!1};
g.h.Nc=function(a,b){this.I=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.I};
g.h.getProgressState=function(){var a=D8(this.g),b=this.player.getVideoData();return{allowSeeking:g.O(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.fc():!a.isAdPlaying()&&this.player.fc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+w8(a):a.l,isAtLiveHead:1>=(a.u?a.i+w8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+w8(a):a.i,seekableStart:0<a.o?a.o+
w8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Wn=function(){this.g&&this.g.Wn()};
g.h.FI=function(a){1==a&&(this.F=this.g?D8(this.g):null)};
g.h.SK=function(){var a=f9()?new C8(a9(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.F=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.F)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,y8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.vz=function(){this.B=[this.i].concat(csa());var a=b9()||this.i;u9(this,a);this.player.la("onMdxReceiversChange")};
g.h.pM=function(a){!this.D&&g.cE(a,8)&&(this.player.pauseVideo(),t9(this))};
g.h.QK=function(){var a=b9();u9(this,a)};
g.h.PK=function(){this.l=b9()};
g.h.vM=function(){this.D=!0;t9(this);h9=!1;i9&&d9(i9,1);i9=null};
g.h.uM=function(){this.D=!1;t9(this);u9(this,this.i);this.l=this.i;h9=!1;i9=null;this.player.playVideo()};
g.h.zc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.B;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?s8():u9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.B.length&&"cast-selector-receiver"==this.B[1].key?(b&&s8(),!0):!1}};
g.h.wt=function(){this.g.wt()};
g.h.Gb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.KV.remote=s9;})(_yt_player);
